apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ include "k8s-api-chart.fullname" . }}
    namespace: {{ .Values.namespace }}
spec:
    replicas: 1
    selector:
        matchLabels:
            app: {{ include "k8s-api-chart.fullname" . }}
    template:
        metadata:
            labels:
                app: {{ include "k8s-api-chart.fullname" . }}
        spec:
            containers:
            - name: {{ include "k8s-api-chart.fullname" . }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              ports:
              - containerPort: {{ .Values.service.targetPort }}