apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: k8s-api-secret
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: k8s-api-env
  data:
    - secretKey: MONGODB_URI       
      remoteRef:
        key: k8s-api/mongodb       
        property: MONGODB_URI              
    - secretKey: MONGODB_DATABASE_NAME
      remoteRef:
        key: k8s-api/mongodb
        property: MONGODB_DATABASE_NAME
    - secretKey: MONGODB_COLLECTION_NAME
      remoteRef:
        key: k8s-api/mongodb
        property: MONGODB_COLLECTION_NAME