apiVersion: apps/v1
kind: Deployment
metadata:
    name: k8s-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: k8s-api
    template:
        metadata:
            labels:
                app: k8s-api
        spec:
            containers:
            - name: k8s-api
              image: k8s-api:latest
              imagePullPolicy: IfNotPresent  # Avoids trying to pull it from the registry
              ports:
              - containerPort: 3000