replicaCount: 1

image:
  repository: account-number.dkr.ecr.region.amazonaws.com/my/api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: api.example.com
      paths:
        - path: /users
          pathType: Prefix
          backend:
            service:
              name: k8s-api
              port:
                number: 80
        - path: /compute
          pathType: Prefix
          backend:
            service:
              name: k8s-api
              port:
                number: 80
        - path: /
          pathType: Prefix
          backend:
            service:
              name: k8s-api
              port:
                number: 80

namespace: api
fullnameOverride: "k8s-api"
envFromSecret: "k8s-api-env"
aws:
  region: us-east-1