name: Deploy Helm Chart
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ vars.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Fetch image digest
        env:
          AWS_REGION: ${{ vars.AWS_REGION }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        run: |
          REPO_NAME=${ECR_REPOSITORY#*.amazonaws.com/}
          IMAGE_DIGEST=$(aws ecr describe-images --repository-name "$REPO_NAME" --image-ids imageTag=latest --query 'imageDetails[0].imageDigest' --output text)
          echo "IMAGE_DIGEST=$IMAGE_DIGEST" >> "$GITHUB_ENV"

      - name: Deploy Helm chart
        run: |
          helm upgrade --install k8s-api ./_infra/k8s-api-chart \
            --namespace api \
            --create-namespace \
            --values ./_infra/k8s-api-chart/values.yaml \
            --set image.digest=$IMAGE_DIGEST \
            --set ingress.hosts[0].host=${{ secrets.INGRESS_HOST }} \
            --set image.repository=${{ secrets.ECR_REPOSITORY }}

      - name: Deploy ingress-nginx
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
            --namespace ingress-nginx \
            --create-namespace \
            --version 4.7.1 \
            --values ./_infra/ingress-nginx-values.yaml