name: Deploy Helm Chart
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ vars.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Deploy Helm chart
        run: |
          helm upgrade --install k8s-api ./_infra/k8s-api-chart \
            --namespace api \
            --create-namespace \
            --values ./_infra/k8s-api-chart/values.yaml \
            --set image.tag=latest \
            --set ingress.hosts[0].host=${{ secrets.INGRESS_HOST }} \
            --set image.repository=${{ secrets.ECR_REPOSITORY }}
