jobs:
  render-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout this k8s-api repo
      - name: Checkout k8s-api repo
        uses: actions/checkout@v3

      # 2. Checkout your GitOps repo
      - name: Checkout GitOps repo
        uses: actions/checkout@v3
        with:
          repository: ${{ vars.GITOPS_REPO }}
          token:      ${{ secrets.GITOPS_TOKEN }}
          path:       gitops

      # 3. Install Helm CLI
      - name: Set up Helm
        uses: azure/setup-helm@v3

      # 4. Render chart into separate files under gitops/apps/k8s-api
      - name: Render k8s-api manifests as individual files
        run: |
          # 4a. Create a temporary output-dir
          TMP_OUT=gitops/apps/k8s-api/_helm_render
          mkdir -p "$TMP_OUT"

          # 4b. Run helm template with output-dir
          helm template k8s-api ./_infra/k8s-api-chart \
            --namespace api \
            --values ./_infra/k8s-api-chart/values.yaml \
            --set image.tag=latest \
            --set ingress.hosts[0].host=${{ secrets.INGRESS_HOST }} \
            --set image.repository=${{ secrets.ECR_REPOSITORY }} \
            --output-dir "$TMP_OUT"

          # 4c. Move each rendered YAML into gitops/apps/k8s-api/
          # Helm will create: gitops/apps/k8s-api/_helm_render/k8s-api/templates/<resource>.yaml
          mkdir -p gitops/apps/k8s-api
          mv "$TMP_OUT"/k8s-api/templates/deployment.yaml gitops/apps/k8s-api/deployment.yaml
          mv "$TMP_OUT"/k8s-api/templates/service.yaml    gitops/apps/k8s-api/service.yaml
          mv "$TMP_OUT"/k8s-api/templates/ingress.yaml    gitops/apps/k8s-api/ingress.yaml

          # 4d. Clean up the temporary folder
          rm -rf "$TMP_OUT"

      # 5. Commit & push only if changed
      - name: Commit & Push changes
        run: |
          cd gitops
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add apps/k8s-api/deployment.yaml \
                  apps/k8s-api/service.yaml \
                  apps/k8s-api/ingress.yaml

          if git diff --cached --quiet; then
            echo "No manifest changes to push"
          else
            git commit -m "ci: sync k8s-api manifests @ ${{ github.sha }}"
            git push origin main
          fi
